<!DOCTYPE html>
<html>
<head>
<style>
a:visited{
    color: black;
}

a:hover{
    color:purple;
}

a:active{
    color:black;
}

.sitemap {
  font-size: 150%;
}

.relative {
    position: relative;
}

div.background {
  background: url(http://cdn.appstorm.net/android.appstorm.net/files/2012/03/Metallic-Background.jpg) repeat;
  border: 2px solid black;
}

div.transbox {
  margin: 10px;
  background-color: #ffffff;
  border: 2px solid black;
  opacity: 0.7;
  filter: alpha(opacity=60); /* For IE8 and earlier */
}

div.transbox p {
  margin: 2%;
  font-weight: bold;
  color: #000000;
}
</style>
</head>
<body>

<div class="background">
  <div class="transbox">
	<div class="relative">
	  <div class="sitemap">
	  <center><p><a href="#">[Project Site]&nbsp;</a><a href="#">[Protosite]&nbsp;</a><a href="#">[Rationale]&nbsp;</a><a href="#">[Blog]&nbsp;</a><a href="#">[Intro]&nbsp;</a></p></center>
	  </div>
	  <center><p><small>Copyright &copy; Team 4x4 2015. All rights reserved.</small></p></center>
	  <center><a href="http://validator.w3.org/check?uri=referer">Validated!</a></center>
	</div>
  </div>
</div>

</body>
</html>
